from __future__ import annotations

from pathlib import Path
import argparse
import sys

# Adjust this import depending on where you place ninja_syntax.py.
# If ninja_syntax.py is next to this script, this works.
from ninja_syntax import Writer


def win_path(path: Path) -> str:
    """Return a Ninja-friendly Windows-style path."""
    return str(path).replace("/", "\\")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Ninja rules for standalone rv32ui riscv-tests."
    )
    parser.add_argument(
        "--repo-root",
        default=Path(__file__).resolve().parents[2],
        type=Path,
        help="Repository root. Default assumes script is under tests/asm.",
    )
    parser.add_argument(
        "--out",
        default="build.ninja",
        type=Path,
        help="Output Ninja file.",
    )
    parser.add_argument(
        "--builddir",
        default=Path("build") / "rv32ui",
        type=Path,
        help="Build directory used inside generated Ninja.",
    )
    parser.add_argument(
        "--cc",
        default="riscv-none-elf-gcc",
        help="RISC-V GCC executable.",
    )
    parser.add_argument(
        "--objcopy",
        default="riscv-none-elf-objcopy",
        help="RISC-V objcopy executable.",
    )
    parser.add_argument(
        "--objdump",
        default="riscv-none-elf-objdump",
        help="RISC-V objdump executable.",
    )
    parser.add_argument(
        "--python",
        default="python",
        help="Python executable used by Ninja.",
    )
    parser.add_argument(
        "--march",
        default="rv32i",
        help="RISC-V march value, e.g. rv32i or rv32g.",
    )
    parser.add_argument(
        "--mabi",
        default="ilp32",
        help="RISC-V ABI value.",
    )
    parser.add_argument(
        "--include-memory-tests",
        action="store_true",
        help="Include lb/lbu/lh/lhu/lw/sb/sh/sw/ld_st/st_ld/ma_data/fence_i.",
    )

    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()

    rv32ui_dir = repo_root / "tests" / "riscv-tests" / "isa" / "rv32ui"
    rv64ui_dir = repo_root / "tests" / "riscv-tests" / "isa" / "rv64ui"
    macros_dir = repo_root / "tests" / "riscv-tests" / "isa" / "macros" / "scalar"
    env_dir = repo_root / "tests" / "scripts"
    bin2hex = repo_root / "scripts" / "bin2hex.py"

    if not rv32ui_dir.exists():
        print(f"error: missing rv32ui directory: {rv32ui_dir}", file=sys.stderr)
        return 1

    if not macros_dir.exists():
        print(f"error: missing macros directory: {macros_dir}", file=sys.stderr)
        return 1

    if not env_dir.exists():
        print(f"error: missing custom env directory: {env_dir}", file=sys.stderr)
        print("expected: tests/riscv-standalone-env/riscv_test.h", file=sys.stderr)
        return 1

    if not (env_dir / "riscv_test.h").exists():
        print(f"error: missing {env_dir / 'riscv_test.h'}", file=sys.stderr)
        return 1

    if not bin2hex.exists():
        print(f"error: missing bin2hex.py: {bin2hex}", file=sys.stderr)
        return 1

    sources = sorted(rv32ui_dir.glob("*.S"))

    # Skip tests that are likely not useful for the current early core unless requested.
    memory_or_special = {
        "lb",
        "lbu",
        "lh",
        "lhu",
        "lw",
        "sb",
        "sh",
        "sw",
        "ld_st",
        "st_ld",
        "ma_data",
        "fence_i",
    }

    if not args.include_memory_tests:
        sources = [s for s in sources if s.stem not in memory_or_special]

    out_path: Path = args.out

    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        n = Writer(f, width=120)

        n.comment("Generated by gen_rv32ui_ninja.py. Do not edit by hand.")
        n.newline()

        n.variable("cc", args.cc)
        n.variable("objcopy", args.objcopy)
        n.variable("objdump", args.objdump)
        n.variable("python", args.python)
        n.variable("builddir", win_path(args.builddir))
        n.newline()

        # Use absolute paths so the generated Ninja can be run from tests/asm
        # without depending on current directory assumptions.
        n.variable("repo_root", win_path(repo_root))
        n.variable("rv32ui_dir", win_path(rv32ui_dir))
        n.variable("rv64ui_dir", win_path(rv64ui_dir))
        n.variable("macros_dir", win_path(macros_dir))
        n.variable("env_dir", win_path(env_dir))
        n.variable("bin2hex", win_path(bin2hex))
        n.newline()

        # Important:
        # - .S needs preprocessing, so use GCC.
        # - custom env must come before upstream includes.
        # - --no-relax avoids linker-generated surprises.
        # - -Ttext=0x0 matches your existing homebrew tests.
        n.variable("march", f"-march={args.march} -mabi={args.mabi}")
        n.variable(
            "gcc_opts",
            "-nostdlib -nostartfiles -ffreestanding -Wl,--no-relax -Wl,-Ttext=0x0",
        )
        n.variable(
            "incflags",
            "-I$env_dir -I$macros_dir -I$rv32ui_dir -I$rv64ui_dir",
        )
        n.newline()

        n.rule(
            "rvtest_elf",
            "$cc $march $gcc_opts $incflags $in -o $out",
            description="RVTEST $out",
        )

        n.rule(
            "dump",
            "$objdump -d $in > $out",
            description="DUMP $out",
        )

        n.rule(
            "objcopy_bin",
            "$objcopy -O binary $in $out",
            description="OBJCOPY $out",
        )

        n.rule(
            "bin_to_hex",
            "$python $bin2hex $in $out",
            description="BIN2HEX $out",
        )

        n.newline()

        defaults: list[str] = []

        for src in sources:
            name = src.stem
            base = f"rv32ui-{name}"

            elf = win_path(args.builddir / f"{base}.elf")
            dump = win_path(args.builddir / f"{base}.dump")
            binary = win_path(args.builddir / f"{base}.bin")
            hex_file = f"tests/asm/riscv/{base}.hex"

            # Use absolute source path for reliability.
            src_path = win_path(src)

            n.build(elf, "rvtest_elf", src_path)
            n.build(dump, "dump", elf)
            n.build(binary, "objcopy_bin", elf)
            n.build(hex_file, "bin_to_hex", binary)
            n.newline()

            defaults.append(hex_file)

        n.default(defaults)

    print(f"wrote {out_path}")
    print(f"generated {len(defaults)} rv32ui tests")
    if not args.include_memory_tests:
        print(
            "memory/special tests skipped; pass --include-memory-tests to include them"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
