from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from ninja_syntax import Writer


def win_path(path: Path) -> str:
    text = str(path)
    if os.name == "nt":
        return text.replace("/", "\\")
    return text


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Ninja rules for standalone rv32ui riscv-tests."
    )
    parser.add_argument(
        "--repo-root",
        default=Path(__file__).resolve().parents[2],
        type=Path,
        help="Repository root. Default assumes script is under tests/asm.",
    )
    parser.add_argument(
        "--out",
        default="build.ninja",
        type=Path,
        help="Output Ninja file.",
    )
    parser.add_argument(
        "--builddir",
        default=Path("build") / "rv32ui",
        type=Path,
        help="Build directory used inside generated Ninja.",
    )
    parser.add_argument(
        "--cc",
        default="riscv64-unknown-elf-gcc",
        help="RISC-V GCC executable.",
    )
    parser.add_argument(
        "--objcopy",
        default="riscv64-unknown-elf-objcopy",
        help="RISC-V objcopy executable.",
    )
    parser.add_argument(
        "--objdump",
        default="riscv64-unknown-elf-objdump",
        help="RISC-V objdump executable.",
    )
    parser.add_argument(
        "--python",
        default="python3",
        help="Python executable used by Ninja.",
    )
    parser.add_argument(
        "--march",
        default="rv32i",
        help="RISC-V march value, e.g. rv32i or rv32g.",
    )
    parser.add_argument(
        "--mabi",
        default="ilp32",
        help="RISC-V ABI value.",
    )

    parser.add_argument(
        "--enable-spike-trace",
        action="store_true",
        help="Also generate Ninja targets that run Spike and convert logs to CSV.",
    )
    parser.add_argument(
        "--spike",
        default="spike",
        help="Spike executable.",
    )

    parser.add_argument(
        "--spike-isa",
        default="RV32I",
        help="Spike ISA string.",
    )

    parser.add_argument(
        "--spike-priv",
        default="m",
        help="Spike privilege mode.",
    )

    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()

    rv32ui_dir = repo_root / "tests" / "riscv-tests" / "isa" / "rv32ui"
    rv64ui_dir = repo_root / "tests" / "riscv-tests" / "isa" / "rv64ui"
    macros_dir = repo_root / "tests" / "riscv-tests" / "isa" / "macros" / "scalar"
    env_dir = repo_root / "tests" / "scripts"
    bin2hex = repo_root / "scripts" / "bin2hex.py"
    spike_to_csv = repo_root / "tests" / "scripts" / "spike_log_to_csv.py"

    if not rv32ui_dir.exists():
        print(f"error: missing rv32ui directory: {rv32ui_dir}", file=sys.stderr)
        return 1

    if not macros_dir.exists():
        print(f"error: missing macros directory: {macros_dir}", file=sys.stderr)
        return 1

    if not env_dir.exists():
        print(f"error: missing custom env directory: {env_dir}", file=sys.stderr)
        print("expected: tests/scripts/riscv_test.h", file=sys.stderr)
        return 1

    if not (env_dir / "riscv_test.h").exists():
        print(f"error: missing {env_dir / 'riscv_test.h'}", file=sys.stderr)
        return 1

    if not bin2hex.exists():
        print(f"error: missing bin2hex.py: {bin2hex}", file=sys.stderr)
        return 1

    if not spike_to_csv.exists():
        print(f"error: missing spike_log_to_csv.py: {spike_to_csv}", file=sys.stderr)
        return 1

    sources = sorted(rv32ui_dir.glob("*.S"))

    unsupported_tests = {
        "fence_i",
    }

    sources = [s for s in sources if s.stem not in unsupported_tests]

    out_path: Path = args.out

    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        n = Writer(f, width=120)

        n.comment("Generated by gen_rv32ui.py. Do not edit by hand.")
        n.newline()

        n.variable("cc", args.cc)
        n.variable("objcopy", args.objcopy)
        n.variable("objdump", args.objdump)
        n.variable("python", args.python)
        n.variable("builddir", win_path(args.builddir))
        n.newline()

        n.variable("spike", args.spike)
        n.variable("spike_isa", args.spike_isa)
        n.variable("spike_priv", args.spike_priv)
        n.newline()

        # Use absolute paths so the generated Ninja can be run from tests/asm
        # without depending on current directory assumptions.
        n.variable("repo_root", win_path(repo_root))
        n.variable("rv32ui_dir", win_path(rv32ui_dir))
        n.variable("rv64ui_dir", win_path(rv64ui_dir))
        n.variable("macros_dir", win_path(macros_dir))
        n.variable("env_dir", win_path(env_dir))
        n.variable("bin2hex", win_path(bin2hex))
        n.variable("spike_log_to_csv", win_path(spike_to_csv))
        n.newline()

        # Important:
        # - .S needs preprocessing, so use GCC.
        # - custom env must come before upstream includes.
        # - --no-relax avoids linker-generated surprises.
        # - -Ttext=0x0 matches your existing homebrew tests.
        n.variable("march", f"-march={args.march} -mabi={args.mabi}")
        linker_script = repo_root / "tests" / "riscv-tests" / "env" / "p" / "link.ld"
        n.variable("linker_script", str(linker_script))
        n.variable(
            "gcc_opts",
            "-nostdlib -nostartfiles -ffreestanding -Wl,--no-relax -Wl,-T,$linker_script",
        )
        n.variable(
            "incflags",
            "-I$env_dir -I$macros_dir -I$rv32ui_dir -I$rv64ui_dir",
        )
        n.newline()

        n.rule(
            "rvtest_elf",
            "$cc $march $gcc_opts $incflags $in -o $out",
            description="RVTEST $out",
        )

        n.rule(
            "dump",
            "$objdump -d $in > $out",
            description="DUMP $out",
        )

        n.rule(
            "objcopy_bin",
            "$objcopy -O binary $in $out",
            description="OBJCOPY $out",
        )

        n.rule(
            "bin_to_hex",
            "$python $bin2hex $in $out",
            description="BIN2HEX $out",
        )

        if args.enable_spike_trace:
            n.rule(
                "spike_log",
                "$spike --isa=$spike_isa --priv=$spike_priv -l --log-commits $in 2> $out",
                description="SPIKE $out",
            )

            n.rule(
                "spike_csv",
                "$python $spike_log_to_csv --log $in --csv $out -f",
                description="SPIKECSV $out",
            )

        n.newline()

        defaults: list[str] = []

        for src in sources:
            name = src.stem
            base = f"rv32ui-{name}"

            elf = win_path(args.builddir / f"{base}.elf")
            dump = win_path(args.builddir / f"{base}.dump")
            binary = win_path(args.builddir / f"{base}.bin")
            hex_file = f"tests/asm/riscv/{base}.hex"

            src_path = win_path(src)

            rv64_src = rv64ui_dir / src.name
            implicit_deps: list[str] = []

            if rv64_src.exists():
                implicit_deps.append(win_path(rv64_src))

            implicit_deps.append(win_path(env_dir / "riscv_test.h"))
            implicit_deps.append(win_path(macros_dir / "test_macros.h"))

            n.build(
                elf,
                "rvtest_elf",
                src_path,
                implicit=implicit_deps,
            )

            n.build(dump, "dump", elf)
            n.build(binary, "objcopy_bin", elf)
            n.build(hex_file, "bin_to_hex", binary)

            if args.enable_spike_trace:
                spike_log = win_path(args.builddir / f"{base}.spike.log")
                spike_csv = win_path(args.builddir / f"{base}.spike.csv")

                n.build(spike_log, "spike_log", elf)
                n.build(spike_csv, "spike_csv", spike_log)

                defaults.append(spike_csv)

            n.newline()

            defaults.append(hex_file)

        n.default(defaults)

    print(f"wrote {out_path}")
    print(f"generated {len(defaults)} rv32ui tests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
